#!/usr/bin/env python3
"""
Merge tools/imported_cn_content.js into data.js (cnEx.skillAttr) and crk/crk_cn_descriptions.js.

  python apply_wiki_cn_content.py
  python apply_wiki_cn_content.py --dry-run --name Fire_spirit
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from typing import Any

import import_wiki_illustrations as illu
import re
from apply_wiki_cookie_data import (
    apply_description_map,
    apply_page_updated_stamp,
    cookie_names_for_description_keys,
    ensure_trailing_comma_on_line,
    find_character_block,
    find_desc_section,
    page_updated_stamp_iso,
    parse_skill_attr_object_from_block_lines,
    skill_attr_objects_equal,
)
from apply_wiki_skill_details import (
    DATA_SKILL_KEY_ORDER,
    find_prop_span,
    insert_point_after_preds,
    load_skill_import,
)

ROOT = illu.ROOT
DEFAULT_DATA = os.path.join(ROOT, "data.js")
DEFAULT_CN_DESC = os.path.join(ROOT, "crk", "crk_cn_descriptions.js")
DEFAULT_IMPORT = os.path.join(ROOT, "tools", "imported_cn_content.js")


def _format_skill_attr_num(x: int | float) -> str:
    xf = float(x)
    if not math.isfinite(xf):
        return json.dumps(xf, ensure_ascii=False)
    if xf == int(xf):
        return f"{int(xf)}.0"
    return json.dumps(xf, ensure_ascii=False).replace(",", "")


def format_cn_ex_skill_attr_lines(obj: dict[str, list[int | float]]) -> list[str]:
    indent = "                        "
    sub = "                            "
    out: list[str] = [f"{indent}skillAttr: {{\n"]
    for ak in sorted(obj.keys()):
        pair = obj[ak]
        out.append(
            f"{sub}{ak}: [{_format_skill_attr_num(pair[0])}, {_format_skill_attr_num(pair[1])}],\n"
        )
    out.append(f"{indent}}},\n")
    return out


def format_cn_ex_block(skill_attr: dict[str, list[int | float]]) -> list[str]:
    return [
        "                    cnEx: {\n",
        *format_cn_ex_skill_attr_lines(skill_attr),
        "                    },\n",
    ]


def _find_cn_ex_skill_attr_span(
    lines: list[str], cn_start: int, cn_end: int
) -> tuple[int, int] | None:
    """skillAttr inside cnEx is indented deeper than top-level character props."""
    for i in range(cn_start + 1, cn_end):
        if not re.match(r"^                        skillAttr:\s", lines[i]):
            continue
        depth = lines[i].count("{") - lines[i].count("}")
        if depth == 0:
            return i, i
        for j in range(i + 1, cn_end + 1):
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0:
                return i, j
    return None


def apply_cn_ex_skill_attr_on_character(
    lines: list[str],
    cookie_name: str,
    wiki_obj: dict[str, list[int | float]],
    dry_run: bool,
    log: list[str],
) -> bool:
    block = find_character_block(lines, cookie_name)
    if not block:
        log.append(f"  [skip data] no block for name={cookie_name!r}")
        return False
    start, end = block
    body_start = start + 1
    body_end = end
    cnex_span = find_prop_span(lines, body_start, body_end, "cnEx")
    skill_attr_lines = format_cn_ex_skill_attr_lines(wiki_obj)

    if cnex_span:
        cn_start, cn_end = cnex_span
        skill_span = _find_cn_ex_skill_attr_span(lines, cn_start, cn_end)
        if skill_span:
            sa_start, sa_end = skill_span
            existing = parse_skill_attr_object_from_block_lines(lines, sa_start, sa_end)
            if skill_attr_objects_equal(existing, wiki_obj):
                return False
            log.append(
                f"  data {cookie_name}.cnEx.skillAttr: updated attr keys {sorted(wiki_obj.keys())}"
            )
            if not dry_run:
                lines[sa_start : sa_end + 1] = skill_attr_lines
            return True

        log.append(f"  data {cookie_name}.cnEx.skillAttr: (insert into existing cnEx)")
        if not dry_run:
            lines[cn_end:cn_end] = skill_attr_lines
            prev_idx = cn_end - 1
            while prev_idx > cn_start and not lines[prev_idx].strip():
                prev_idx -= 1
            if prev_idx > cn_start:
                lines[prev_idx] = ensure_trailing_comma_on_line(lines[prev_idx])
        return True

    log.append(f"  data {cookie_name}.cnEx: (insert)")
    if not dry_run:
        ins = insert_point_after_preds(lines, body_start, body_end, "skillAttr")
        lines[ins] = ensure_trailing_comma_on_line(lines[ins])
        lines[ins + 1 : ins + 1] = format_cn_ex_block(wiki_obj)
    return True


def _ensure_cn_desc_file(path: str) -> list[str]:
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            return f.readlines()
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    stub = (
        "// CN Kingdom (冲呀！饼干人：王国) skill text — generated by import_wiki_cn_content.py\n"
        "window.CRK_CN_DESCRIPTIONS = {\n"
        "  skill_details: {\n"
        "  },\n"
        "  skill_notes: {\n"
        "  },\n"
        "  rally_effects: {\n"
        "  },\n"
        "};\n"
    )
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(stub)
    with open(path, encoding="utf-8") as f:
        return f.readlines()


def apply_cn_import_doc(
    doc: dict[str, Any],
    *,
    dry_run: bool = False,
    filter_name: str | None = None,
    data_js: str = DEFAULT_DATA,
    cn_descriptions_js: str = DEFAULT_CN_DESC,
    no_data: bool = False,
    no_descriptions: bool = False,
) -> tuple[bool, bool, list[str]]:
    cookies: dict[str, Any] = dict(doc.get("cookies") or {})
    if filter_name:
        if filter_name not in cookies:
            print(f"No cookie {filter_name!r} in CN import", file=sys.stderr)
            raise SystemExit(1)
        cookies = {filter_name: cookies[filter_name]}

    log: list[str] = []
    data_changed = False
    desc_changed = False
    stamp = page_updated_stamp_iso()
    stamp_names: set[str] = set()
    processed_names = set(cookies.keys())
    desc_keys_touched: set[str] = set()
    data_lines: list[str] | None = None

    if not no_data:
        with open(data_js, encoding="utf-8") as f:
            data_lines = f.readlines()
        for cname, payload in cookies.items():
            attrs = payload.get("skillAttr")
            if isinstance(attrs, dict) and attrs:
                if apply_cn_ex_skill_attr_on_character(
                    data_lines, cname, attrs, dry_run, log
                ):
                    data_changed = True
                    stamp_names.add(cname)

    if not no_descriptions:
        desc_lines = _ensure_cn_desc_file(cn_descriptions_js)
        all_details: dict[str, str] = {}
        all_notes: dict[str, str] = {}
        all_rally: dict[str, str] = {}

        for cname, payload in cookies.items():
            base = illu.cookie_name_to_wiki_slug(cname)
            if sd := payload.get("skill_details"):
                all_details[base] = sd
            if sn := payload.get("skill_notes"):
                all_notes[base] = sn
            if ry := payload.get("rally_effects"):
                all_rally[base] = ry

        if all_details:
            sec = find_desc_section(desc_lines, "  skill_details: {", "  skill_notes:")
            if not sec:
                print("Lost skill_details section in crk_cn_descriptions.js", file=sys.stderr)
                raise SystemExit(1)
            ch, keys = apply_description_map(
                desc_lines, sec[0], sec[1], all_details, dry_run, log, "cn skill_details"
            )
            if ch:
                desc_changed = True
                desc_keys_touched.update(keys)

        if all_notes:
            sec = find_desc_section(desc_lines, "  skill_notes: {", "  rally_effects:")
            if not sec:
                print("Lost skill_notes section in crk_cn_descriptions.js", file=sys.stderr)
                raise SystemExit(1)
            ch, keys = apply_description_map(
                desc_lines, sec[0], sec[1], all_notes, dry_run, log, "cn skill_notes"
            )
            if ch:
                desc_changed = True
                desc_keys_touched.update(keys)

        if all_rally:
            sec = find_desc_section(desc_lines, "  rally_effects: {", "};")
            if not sec:
                print("Lost rally_effects section in crk_cn_descriptions.js", file=sys.stderr)
                raise SystemExit(1)
            ch, keys = apply_description_map(
                desc_lines, sec[0], sec[1], all_rally, dry_run, log, "cn rally_effects"
            )
            if ch:
                desc_changed = True
                desc_keys_touched.update(keys)

        if desc_changed and not dry_run:
            with open(cn_descriptions_js, "w", encoding="utf-8", newline="\n") as f:
                f.writelines(desc_lines)

    if not no_data:
        stamp_names.update(
            cookie_names_for_description_keys(desc_keys_touched, list(cookies.keys()))
        )

    page_updated_changed = False
    if not no_data and data_lines is not None:
        for n in sorted(processed_names | stamp_names):
            changed = apply_page_updated_stamp(
                data_lines,
                n,
                stamp,
                dry_run,
                log,
                update_existing=(n in stamp_names),
            )
            page_updated_changed = page_updated_changed or changed
        if not dry_run and (data_changed or page_updated_changed):
            with open(data_js, "w", encoding="utf-8", newline="\n") as f:
                f.writelines(data_lines)

    return (not no_data) and (data_changed or page_updated_changed), desc_changed, log


def main() -> None:
    ap = argparse.ArgumentParser(description="Apply CN Kingdom wiki import")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--name", help="Only this data.js cookie name")
    ap.add_argument("--import-path", default=DEFAULT_IMPORT)
    ap.add_argument("--data-js", default=DEFAULT_DATA)
    ap.add_argument("--cn-descriptions-js", default=DEFAULT_CN_DESC)
    ap.add_argument("--no-data", action="store_true")
    ap.add_argument("--no-descriptions", action="store_true")
    args = ap.parse_args()

    try:
        doc = load_skill_import(args.import_path)
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(f"Failed to load {args.import_path}: {e}", file=sys.stderr)
        sys.exit(1)

    data_changed, desc_changed, log = apply_cn_import_doc(
        doc,
        dry_run=args.dry_run,
        filter_name=args.name,
        data_js=args.data_js,
        cn_descriptions_js=args.cn_descriptions_js,
        no_data=args.no_data,
        no_descriptions=args.no_descriptions,
    )

    if log:
        print("Changes:")
        for line in log:
            print(line)
    else:
        print("No differences to apply.")

    if args.dry_run and (data_changed or desc_changed):
        print("(dry-run: no files written)")


if __name__ == "__main__":
    main()
