const cookieByDate = [
    "GingerBrave",
    "Strawberry Cookie",
    "Wizard Cookie",
    "Ninja Cookie",
    "Angel Cookie",
    "Muscle Cookie",
    "Beet Cookie", 
    "Custard Cookie III",
    "Blackberry Cookie",
    "Avocado Cookie",
    "Carrot Cookie",
    "Cherry Cookie",
    "Onion Cookie",
    "Knight Cookie",
    "Gumball Cookie",
    "Adventurer Cookie",
    "Alchemist Cookie",
    "Pancake Cookie",
    "Clover Cookie",
    "Princess Cookie",
    "Chili Pepper Cookie",
    "Herb Cookie",
    "Tiger Lily Cookie",
    "Mint Choco Cookie",
    "Werewolf Cookie",
    "Dark Choco Cookie",
    "Licorice Cookie",
    "Sparkling Cookie",
    "Vampire Cookie",
    "Milk Cookie",
    "Pomegranate Cookie",
    "Poison Mushroom Cookie",
    "Purple Yam Cookie",
    "Rye Cookie",
    "Espresso Cookie",
    "Snow Sugar Cookie",
    "Madeleine Cookie",
    "Kumiho Cookie",
    "Cream Puff Cookie",
    "Latte Cookie",
    "Almond Cookie",
    "Black Raisin Cookie",
    "Pure Vanilla Cookie",
    "Strawberry Crepe Cookie",
    "Fig Cookie",
    "Pastry Cookie",
    "Devil Cookie",
    "Red Velvet Cookie",
    "Mango Cookie",
    "Sea Fairy Cookie",
    "Lilac Cookie",
    "Sorbet Shark Cookie",
    "Squid Ink Cookie",
    "Parfait Cookie",
    "Hollyberry Cookie",
    "Raspberry Cookie",
    "Moon Rabbit Cookie",
    "Sonic Cookie",
    "Tails Cookie",
    "Mala Sauce Cookie",
    "Twizzly Gummy Cookie",
    "Pumpkin Pie Cookie",
    "Cotton Cookie",
    "Frost Queen Cookie",
    "Cocoa Cookie",
    "Eclair Cookie",
    "Tea Knight Cookie",
    "Affogato Cookie",
    "Dark Cacao Cookie",
    "Caramel Arrow Cookie",
    "Cherry Blossom Cookie",
    "Clotted Cream Cookie",
    "Wildberry Cookie",
    "Crunchy Chip Cookie",
    "Oyster Cookie",
    "Financier Cookie",
    "Aladdin Cookie",
    "Alice Cookie",
    "Ariel Cookie",
    "Beast Cookie",
    "Belle Cookie",
    "Cinderella Cookie",
    "Daisy Duck Cookie",
    "Donald Duck Cookie",
    "Goofy Cookie",
    "Jasmine Cookie",
    "Lilo Cookie",
    "Mickey Mouse Cookie",
    "Minnie Mouse Cookie",
    "Mulan Cookie",
    "Peter Pan Cookie",
    "Pocahontas Cookie",
    "Princess Aurora Cookie",
    "Snow White Cookie",
    "Stitch Cookie",
    "Tinker Bell Cookie",
    "Cream Unicorn Cookie",
    "Black Pearl Cookie",
    "Captain Caviar Cookie",
    "Candy Diver Cookie",
    "J-hope Cookie",
    "Jimin Cookie",
    "Jin Cookie",
    "Jung Kook Cookie",
    "RM Cookie",
    "Schwarzwälder",
    "SUGA Cookie",
    "V Cookie",
    "BTS",
    "Macaron Cookie",
    "Carol Cookie",
    "Sherbet Cookie",
    "Pinecone Cookie",
    "Prophet Cookie",
    "Milky Way Cookie",
    "Moonlight Cookie",
    "Blueberry Pie Cookie",
    "Space Doughnut",
    "Stardust Cookie",
    "Capsaicin Cookie",
    "Prune Juice Cookie",
    "Kouign-Amann Cookie",
    "Pitaya Dragon Cookie",
    "Royal Margarine Cookie",
    "Snapdragon Cookie",
    "Tarte Tatin Cookie",
    "Rockstar Cookie",
    "Shining Glitter Cookie",
    "Black Lemonade Cookie",
    "Peppermint Cookie",
    "Aquamarine Cookie",
    "Crimson Coral Cookie",
    "Gold Citrine Cookie",
    "Mystic Opal Cookie",
    "Frilled Jellyfish Cookie",
    "Burnt Cheese Cookie",
    "Golden Cheese Cookie",
    "Fettuccine Cookie",
    "Mozzarella Cookie",
    "Olive Cookie",
    "Icicle Yeti Cookie",
    "Crème Brûlée Cookie",
    "Linzer Cookie",
    "Rebel Cookie",
    "Silverbell Cookie",
    "White Lily Cookie",
    "Mercurial Knight Cookie",
    "Elder Faerie Cookie",
    "Matcha Cookie",
    "Butter Roll Cookie",
    "Witchberry Cookie",
    "Caramel Choux Cookie",
    "Street Urchin Cookie",
    "Stormbringer Cookie",
    "Cloud Haetae Cookie",
    "Mystic Flour Cookie",
    "Twisted Donut Cookie",
    "Dark Cacao Cookie (Dragon Lord)",
    "Peach Blossom Cookie",
    "Cream Ferret Cookie",
    "MyCookie",
    "Star Coral Cookie",
    "Wind Archer Cookie",
    "Burning Spice Cookie",
    "Nutmeg Tiger Cookie",
    "Smoked Cheese Cookie",
    "Golden Cheese Cookie (Immortal)",
    "Young Kulfi",
    "Camellia Cookie",
    "Golden Osmanthus Cookie",
    "Red Osmanthus Cookie",
    "Choco Drizzle Cookie",
    "Pudding à la Mode Cookie",
    "Green Tea Mousse Cookie",
    "Okchun Cookie",
    "Rainbow Sherbet Cookie",
    "Candy Apple Cookie",
    "Shadow Milk Cookie",
    "Black Sapphire Cookie",
    "Pure Vanilla Cookie (Compassionate)",
    "Black Forest Cookie",
    "Wedding Cake Cookie",
    "Agar Agar Cookie",
    "Fire Spirit Cookie",
    "Eternal Sugar Cookie",
    "Pavlova Cookie",
    "Hollyberry Cookie (Aegis)",
    "Sugarfly Cookie",
    "Cream Soda Cookie",
    "Lemon Cookie",
    "Marshmallow Bunny Cookie",
    "Orange Cookie",
    "Lime Cookie",
    "Jagae Cookie",
    "Manju Cookie",
    "Grapefruit Cookie",
    "Seltzer Cookie",
    "Doughael",
    "Menthol Cookie",
    "Charcoal Cookie",
    "Silent Salt Cookie",
    "Salt Cellar Cookie",
    "White Lily Cookie (Dawnbringer)",
    "Chess Choco Cookie",
    "Elphaba Cookie",
    "Glinda Cookie",
    "Millennial Tree Cookie",
    "Dark Enchantress Cookie",
    "Mold Dough Cookie",
    "Venom Dough Cookie",
    "Pom-pom Dough Cookie",
    "Sugar Swan Cookie"
]

// Magic Candy release order (cookie displayNames, for future MC-specific sorting)
const candyByDate = [
    "Espresso Cookie",
    "Purple Yam Cookie",
    "Vampire Cookie",
    "Milk Cookie",
    "Rye Cookie",
    "Squid Ink Cookie",
    "Werewolf Cookie",
    "Licorice Cookie",
    "Cream Puff Cookie",
    "Mala Sauce Cookie",
    "Latte Cookie",
    "Madeleine Cookie",
    "Tea Knight Cookie",
    "Wildberry Cookie",
    "Mango Cookie",
    "Parfait Cookie",
    "Sea Fairy Cookie",
    "Black Pearl Cookie",
    "Sorbet Shark Cookie",
    "Black Raisin Cookie",
    "Snow Sugar Cookie",
    "Financier Cookie",
    "Pinecone Cookie",
    "Captain Caviar Cookie",
    "Cream Unicorn Cookie",
    "Strawberry Crepe Cookie",
    "Twizzly Gummy Cookie",
    "Blueberry Pie Cookie",
    "Caramel Arrow Cookie",
    "Dark Choco Cookie",
    "Moonlight Cookie",
    "Mint Choco Cookie",
    "Pastry Cookie",
    "Peppermint Cookie",
    "Frilled Jellyfish Cookie",
    "Sparkling Cookie",
    "Kouign-Amann Cookie",
    "Raspberry Cookie",
    "Stormbringer Cookie",
    "Silverbell Cookie",
    "Green Tea Mousse Cookie",
    "Wind Archer Cookie",
    "Poison Mushroom Cookie",
    "Pomegranate Cookie",
    "Frost Queen Cookie"
]
