// Version keys must be quoted strings — unquoted 3.10 becomes 3.1 and overwrites 3.1, etc.
const cookieByDate = {
    "1.0": ["GingerBrave", "Strawberry Cookie", "Wizard Cookie", "Ninja Cookie", "Angel Cookie", "Muscle Cookie", "Beet Cookie", "Custard Cookie III", 
        "Blackberry Cookie", "Avocado Cookie", "Carrot Cookie", "Cherry Cookie", "Onion Cookie", "Knight Cookie", "Gumball Cookie", "Adventurer Cookie", 
        "Alchemist Cookie", "Pancake Cookie", "Clover Cookie", "Princess Cookie", "Chili Pepper Cookie", "Herb Cookie", "Tiger Lily Cookie", "Mint Choco Cookie", 
        "Werewolf Cookie", "Dark Choco Cookie", "Licorice Cookie", "Sparkling Cookie", "Vampire Cookie", "Milk Cookie", "Pomegranate Cookie", "Poison Mushroom Cookie", 
        "Purple Yam Cookie", "Rye Cookie", "Snow Sugar Cookie", "Madeleine Cookie", "Espresso Cookie"],
    "1.1": ["Kumiho Cookie"],
    "1.2": ["Cream Puff Cookie", "Latte Cookie", "Almond Cookie"],
    "1.3": ["Pure Vanilla Cookie", "Black Raisin Cookie", "Strawberry Crepe Cookie"],
    "1.4": ["Fig Cookie", "Pastry Cookie"],
    "1.5": ["Red Velvet Cookie", "Devil Cookie"],
    "1.6": ["Sea Fairy Cookie", "Mango Cookie"],
    "1.7": ["Lilac Cookie"],
    "1.8": ["Squid Ink Cookie", "Sorbet Shark Cookie"],
    "1.9": ["Parfait Cookie"],
    "2.0": ["Raspberry Cookie", "Hollyberry Cookie"],
    "2.1": ["Moon Rabbit Cookie", "Tails Cookie", "Sonic Cookie"],
    "2.2": ["Mala Sauce Cookie", "Twizzly Gummy Cookie"],
    "2.3": ["Pumpkin Pie Cookie"],
    "2.4": ["Frost Queen Cookie", "Cotton Cookie"],
    "2.5": ["Cocoa Cookie"],
    "2.6": ["Tea Knight Cookie", "Eclair Cookie"],
    "2.7": ["Affogato Cookie", "Dark Cacao Cookie"],
    "2.8": ["Caramel Arrow Cookie"],
    "2.9": ["Cherry Blossom Cookie"],
    "3.0": ["Clotted Cream Cookie", "Wildberry Cookie"],
    "3.1": ["Crunchy Chip Cookie"],
    "3.2": ["Oyster Cookie"],
    "3.3": ["Financier Cookie"],
    "3.4": ["Cream Unicorn Cookie", "Aladdin Cookie", "Alice Cookie", "Ariel Cookie", "Beast Cookie", "Belle Cookie", "Cinderella Cookie", "Daisy Duck Cookie", 
        "Donald Duck Cookie", "Goofy Cookie", "Jasmine Cookie", "Lilo Cookie", "Mickey Mouse Cookie", "Minnie Mouse Cookie", "Mulan Cookie", "Peter Pan Cookie", 
        "Pocahontas Cookie", "Princess Aurora Cookie", "Snow White Cookie", "Stitch Cookie", "Tinker Bell Cookie"],
    "3.6": ["Black Pearl Cookie", "Captain Caviar Cookie"],
    "3.7": ["Candy Diver Cookie"],
    "3.8": ["Schwarzwälder", "RM Cookie", "Jin Cookie", "SUGA Cookie", "J-hope Cookie", "Jimin Cookie", "V Cookie", "Jung Kook Cookie", "BTS"],
    "3.9": ["Macaron Cookie"],
    "3.10": ["Sherbet Cookie", "Carol Cookie"],
    "3.11": ["Pinecone Cookie"],
    "3.12": ["Prophet Cookie"],
    "4.0": ["Milky Way Cookie", "Moonlight Cookie"],
    "4.1": ["Blueberry Pie Cookie"],
    "4.2": ["Stardust Cookie", "Space Doughnut"],
    "4.3": ["Capsaicin Cookie", "Prune Juice Cookie"],
    "4.4": ["Kouign-Amann Cookie"],
    "4.5": ["Pitaya Dragon Cookie", "Royal Margarine Cookie"],
    "4.6": ["Tarte Tatin Cookie", "Snapdragon Cookie"],
    "4.7": ["Shining Glitter Cookie", "Rockstar Cookie"],
    "4.8": ["Black Lemonade Cookie"],
    "4.9": ["Peppermint Cookie"],
    "4.10": ["Crimson Coral Cookie", "Aquamarine Cookie", "Gold Citrine Cookie", "Mystic Opal Cookie", "Frilled Jellyfish Cookie"],
    "4.11": ["Golden Cheese Cookie", "Burnt Cheese Cookie"],
    "4.12": ["Fettuccine Cookie"],
    "4.13": ["Mozzarella Cookie", "Olive Cookie"],
    "4.14": ["Icicle Yeti Cookie"],
    "4.15": ["Crème Brûlée Cookie", "Linzer Cookie"],
    "4.16": ["Rebel Cookie"],
    "5.0": ["White Lily Cookie", "Silverbell Cookie"],
    "5.1": ["Mercurial Knight Cookie"],
    "5.2": ["Elder Faerie Cookie", "Matcha Cookie", "Butter Roll Cookie", "Witchberry Cookie"],
    "5.3": ["Caramel Choux Cookie", "Street Urchin Cookie"],
    "5.4": ["Stormbringer Cookie"],
    "5.5": ["Mystic Flour Cookie", "Cloud Haetae Cookie", "Twisted Donut Cookie"],
    "5.6": ["Dark Cacao Cookie (Dragon Lord)", "Peach Blossom Cookie"],
    "5.7": ["Cream Ferret Cookie", "MyCookie"],
    "5.8": ["Star Coral Cookie"],
    "5.9": ["Wind Archer Cookie"],
    "5.10": ["Burning Spice Cookie", "Nutmeg Tiger Cookie"],
    "5.11": ["Golden Cheese Cookie (Immortal)", "Smoked Cheese Cookie", "Young Kulfi"],
    "5.12": ["Camellia Cookie", "Golden Osmanthus Cookie", "Red Osmanthus Cookie"],
    "5.13": ["Choco Drizzle Cookie", "Pudding à la Mode Cookie", "Green Tea Mousse Cookie", "Okchun Cookie", "Rainbow Sherbet Cookie"],
    "6.0": ["Shadow Milk Cookie", "Candy Apple Cookie"],
    "6.1": [ "Pure Vanilla Cookie (Compassionate)", "Black Sapphire Cookie"],
    "6.2": ["Wedding Cake Cookie", "Black Forest Cookie"],
    "6.3": ["Fire Spirit Cookie", "Agar Agar Cookie"],
    "6.4": ["Eternal Sugar Cookie", "Pavlova Cookie"],
    "6.5": ["Hollyberry Cookie (Aegis)", "Sugarfly Cookie", "Cream Soda Cookie"],
    "6.6": ["Marshmallow Bunny Cookie", "Lemon Cookie", "Orange Cookie"],
    "6.7": ["Jagae Cookie", "Manju Cookie", "Lime Cookie", "Grapefruit Cookie"],
    "6.8": ["Doughael", "Menthol Cookie", "Seltzer Cookie"],
    "6.9": ["Silent Salt Cookie", "Charcoal Cookie"],
    "6.10": ["White Lily Cookie (Dawnbringer)", "Salt Cellar Cookie"],
    "6.11": ["Chess Choco Cookie", "Elphaba Cookie", "Glinda Cookie"],
    "6.12": ["Millennial Tree Cookie"],
    "7.0": ["Dark Enchantress Cookie", "Mold Dough Cookie"],
    "7.1": ["Venom Dough Cookie", "Pom-pom Dough Cookie"],
    "7.2": ["Sugar Swan Cookie", "Melon Soda Cookie"],
    "7.3": ["Zoey Cookie", "Mira Cookie", "Rumi Cookie", "Abbey Cookie", "Baby Cookie", "Jinu Cookie", "Mystery Cookie", "Romance Cookie", "Derpy & Sussie"],
    "7.4": ["Timekeeper Cookie", "Ash Salt Cookie", "Croissant Cookie"],
    "7.5": ["Povidone-Iodine Cookie", "Litmus Cookie"],
    "7.6": ["Ananas Dragon Cookie"],
    "7.7": ["Nether Queen Cookie", "Asphodel Cookie", "Dark Cherry Cookie"],
    "7.8": ["Time Shadow Cookie", "Pulpo Cookie"],
    "7.9": ["Rajapendra Cookie", "Mogra Cookie"]
}
// Magic Candy release order (cookie displayNames, for future MC-specific sorting)

const candyByDate = {
    "3.3": ["Espresso Cookie", "Purple Yam Cookie", "Vampire Cookie"],
    "3.5": ["Milk Cookie", "Rye Cookie"],
    "3.7": ["Squid Ink Cookie"],
    "3.9": ["Werewolf Cookie"],
    "3.11": ["Licorice Cookie"],
    "4.1": ["Cream Puff Cookie"],
    "4.3": ["Mala Sauce Cookie"],
    "4.4": ["Latte Cookie", "Madeleine Cookie"],
    "4.6": ["Tea Knight Cookie", "Wildberry Cookie"],
    "4.8": ["Mango Cookie", "Parfait Cookie"],
    "4.9": ["Sea Fairy Cookie", "Black Pearl Cookie"],
    "4.10": ["Sorbet Shark Cookie"],
    "4.12": ["Black Raisin Cookie"],
    "4.14": ["Frost Queen Cookie", "Snow Sugar Cookie"],
    "4.16": ["Financier Cookie", "Pinecone Cookie", "Captain Caviar Cookie", "Cream Unicorn Cookie"],
    "5.3": ["Strawberry Crepe Cookie"],
    "5.4": ["Twizzly Gummy Cookie", "Blueberry Pie Cookie"],
    "5.5": ["Caramel Arrow Cookie"],
    "5.6": ["Dark Choco Cookie"],
    "5.8": ["Moonlight Cookie"],
    "5.9": ["Mint Choco Cookie", "Pastry Cookie"],
    "5.10": ["Peppermint Cookie"],
    "5.11": ["Frilled Jellyfish Cookie"],
    "6.1": ["Sparkling Cookie", "Kouign-Amann Cookie"],
    "6.5": ["Raspberry Cookie"],
    "6.6": ["Stormbringer Cookie"],
    "6.10": ["Silverbell Cookie", "Green Tea Mousse Cookie"],
    "6.12": ["Wind Archer Cookie"],
    "7.1": ["Poison Mushroom Cookie", "Pomegranate Cookie"],
    "7.6": ["Mozzarella Cookie"],
    "7.8": ["Fire Spirit Cookie"],
}

const treasureByDate = {
    "1.1": ["Sacred Pomegranate Branch"],
    "1.2": ["Bookseller's Monocle"],
    "1.5": ["Librarian's Encahnted Robes", "Blind Healer's Staff", "Ginkoblin's Trophy Safe"],
}
