const cookieByDate = [
    "GingerBrave",
    "Strawberry Cookie",
    "Wizard Cookie",
    "Ninja Cookie",
    "Angel Cookie",
    "Muscle Cookie",
    "Beet Cookie", 
    "Custard Cookie III",
    "Blackberry Cookie",
    "Avocado Cookie",
    "Carrot Cookie",
    "Cherry Cookie",
    "Onion Cookie",
    "Knight Cookie",
    "Gumball Cookie",
    "Adventurer Cookie",
    "Alchemist Cookie",
    "Pancake Cookie",
    "Clover Cookie",
    "Princess Cookie",
    "Chili Pepper Cookie",
    "Herb Cookie",
    "Tiger Lily Cookie",
    "Mint Choco Cookie",
    "Werewolf Cookie",
    "Dark Choco Cookie",
    "Licorice Cookie",
    "Sparkling Cookie",
    "Vampire Cookie",
    "Milk Cookie",
    "Pomegranate Cookie",
    "Poison Mushroom Cookie",
    "Purple Yam Cookie",
    "Rye Cookie",
    "Espresso Cookie",
    "Snow Sugar Cookie",
    "Madeleine Cookie",
    "Kumiho Cookie",
    "Cream Puff Cookie",
    "Latte Cookie",
    "Almond Cookie",
    "Black Raisin Cookie",
    "Pure Vanilla Cookie",
    "Strawberry Crepe Cookie",
    "Fig Cookie",
    "Pastry Cookie",
    "Red Velvet Cookie",
    "Devil Cookie",
    "Mango Cookie",
    "Sea Fairy Cookie",
    "Lilac Cookie",
    "Squid Ink Cookie",
    "Sorbet Shark Cookie",
    "Parfait Cookie",
    "Raspberry Cookie",
    "Hollyberry Cookie",
    "Moon Rabbit Cookie",
    "Sonic Cookie",
    "Tails Cookie",
    "Mala Sauce Cookie",
    "Twizzly Gummy Cookie",
    "Pumpkin Pie Cookie",
    "Cotton Cookie",
    "Frost Queen Cookie",
    "Cocoa Cookie",
    "Eclair Cookie",
    "Tea Knight Cookie",
    "Affogato Cookie",
    "Dark Cacao Cookie",
    "Caramel Arrow Cookie",
    "Cherry Blossom Cookie",
    "Clotted Cream Cookie",
    "Wildberry Cookie",
    "Crunchy Chip Cookie",
    "Oyster Cookie",
    "Financier Cookie",
    "Aladdin Cookie",
    "Alice Cookie",
    "Ariel Cookie",
    "Beast Cookie",
    "Belle Cookie",
    "Cinderella Cookie",
    "Daisy Duck Cookie",
    "Donald Duck Cookie",
    "Goofy Cookie",
    "Jasmine Cookie",
    "Lilo Cookie",
    "Mickey Mouse Cookie",
    "Minnie Mouse Cookie",
    "Mulan Cookie",
    "Peter Pan Cookie",
    "Pocahontas Cookie",
    "Princess Aurora Cookie",
    "Snow White Cookie",
    "Stitch Cookie",
    "Tinker Bell Cookie",
    "Cream Unicorn Cookie",
    "Captain Caviar Cookie",
    "Black Pearl Cookie",
    "Candy Diver Cookie",
    "J-hope Cookie",
    "Jimin Cookie",
    "Jin Cookie",
    "Jung Kook Cookie",
    "RM Cookie",
    "SUGA Cookie",
    "V Cookie",
    "BTS",
    "Schwarzwälder",
    "Macaron Cookie",
    "Sherbet Cookie",
    "Carol Cookie",
    "Pinecone Cookie",
    "Prophet Cookie",
    "Milky Way Cookie",
    "Moonlight Cookie",
    "Blueberry Pie Cookie",
    "Stardust Cookie",
    "Space Doughnut",
    "Capsaicin Cookie",
    "Prune Juice Cookie",
    "Kouign-Amann Cookie",
    "Pitaya Dragon Cookie",
    "Royal Margarine Cookie",
    "Tarte Tatin Cookie",
    "Snapdragon Cookie",
    "Shining Glitter Cookie",
    "Rockstar Cookie",
    "Black Lemonade Cookie",
    "Peppermint Cookie",
    "Aquamarine Cookie",
    "Gold Citrine Cookie",
    "Mystic Opal Cookie",
    "Crimson Coral Cookie",
    "Frilled Jellyfish Cookie",
    "Golden Cheese Cookie",
    "Burnt Cheese Cookie",
    "Fettuccine Cookie",
    "Mozzarella Cookie",
    "Olive Cookie",
    "Icicle Yeti Cookie",
    "Crème Brûlée Cookie",
    "Linzer Cookie",
    "Rebel Cookie",
    "Silverbell Cookie",
    "White Lily Cookie",
    "Mercurial Knight Cookie",
    "Matcha Cookie",
    "Elder Faerie Cookie",
    "Butter Roll Cookie",
    "Witchberry Cookie",
    "Caramel Choux Cookie",
    "Street Urchin Cookie",
    "Stormbringer Cookie",
    "Mystic Flour Cookie",
    "Cloud Haetae Cookie",
    "Twisted Donut Cookie",
    "Dark Cacao Cookie (Dragon Lord)",
    "Peach Blossom Cookie",
    "Cream Ferret Cookie",
    "MyCookie",
    "Star Coral Cookie",
    "Wind Archer Cookie",
    "Burning Spice Cookie",
    "Nutmeg Tiger Cookie",
    "Golden Cheese Cookie (Immortal)",
    "Smoked Cheese Cookie",
    "Young Kulfi",
    "Camellia Cookie",
    "Golden Osmanthus Cookie",
    "Red Osmanthus Cookie",
    "Choco Drizzle Cookie",
    "Pudding à la Mode Cookie",
    "Green Tea Mousse Cookie",
    "Okchun Cookie",
    "Rainbow Sherbet Cookie",
    "Shadow Milk Cookie",
    "Candy Apple Cookie",
    "Black Sapphire Cookie",
    "Pure Vanilla Cookie (Compassionate)",
    "Wedding Cake Cookie",
    "Black Forest Cookie",
    "Fire Spirit Cookie",
    "Agar Agar Cookie",
    "Eternal Sugar Cookie",
    "Pavlova Cookie",
    "Hollyberry Cookie (Aegis)",
    "Sugarfly Cookie",
    "Cream Soda Cookie",
    "Marshmallow Bunny Cookie",
    "Lemon Cookie",
    "Orange Cookie",
    "Jagae Cookie",
    "Manju Cookie",
    "Lime Cookie",
    "Grapefruit Cookie",
    "Doughael",
    "Menthol Cookie",
    "Seltzer Cookie",
    "Silent Salt Cookie",
    "Charcoal Cookie",
    "Salt Cellar Cookie",
    "White Lily Cookie (Dawnbringer)",
    "Chess Choco Cookie",
    "Elphaba Cookie",
    "Glinda Cookie",
    "Millennial Tree Cookie",
    "Dark Enchantress Cookie",
    "Mold Dough Cookie",
    "Venom Dough Cookie",
    "Pom-pom Dough Cookie",
    "Sugar Swan Cookie"
]

// Magic Candy release order (cookie displayNames, for future MC-specific sorting)
const candyByDate = [
    "Espresso Cookie",
    "Purple Yam Cookie",
    "Vampire Cookie",
    "Milk Cookie",
    "Rye Cookie",
    "Squid Ink Cookie",
    "Werewolf Cookie",
    "Licorice Cookie",
    "Cream Puff Cookie",
    "Mala Sauce Cookie",
    "Latte Cookie",
    "Madeleine Cookie",
    "Tea Knight Cookie",
    "Wildberry Cookie",
    "Mango Cookie",
    "Parfait Cookie",
    "Sea Fairy Cookie",
    "Black Pearl Cookie",
    "Sorbet Shark Cookie",
    "Black Raisin Cookie",
    "Snow Sugar Cookie",
    "Financier Cookie",
    "Pinecone Cookie",
    "Captain Caviar Cookie",
    "Cream Unicorn Cookie",
    "Strawberry Crepe Cookie",
    "Twizzly Gummy Cookie",
    "Blueberry Pie Cookie",
    "Caramel Arrow Cookie",
    "Dark Choco Cookie",
    "Moonlight Cookie",
    "Mint Choco Cookie",
    "Pastry Cookie",
    "Peppermint Cookie",
    "Frilled Jellyfish Cookie",
    "Sparkling Cookie",
    "Kouign-Amann Cookie",
    "Raspberry Cookie",
    "Stormbringer Cookie",
    "Silverbell Cookie",
    "Green Tea Mousse Cookie",
    "Wind Archer Cookie",
    "Poison Mushroom Cookie",
    "Pomegranate Cookie",
    "Frost Queen Cookie"
]
