window.registerGameData({
    id: "crk",
            tierlists: [
                {
                name: "Cookies",
                features: {
                    eidolon: false,
                    tags: false,
                    elementIcon: false,
                    role: false
                },
                filters: {
                        rarity: [
                            "Witch",
                            "Beast",
                            "Ancient",
                            "Legendary",
                            "Dragon",
                            "Super Epic",
                            "Epic",
                        "Special",
                            "Rare",
                            "Common"
                        ],
                        role: [
                            "Ambush",
                            "Bomber",
                            "Charge",
                            "Defense",
                            "Healing",
                            "Magic",
                            "Ranged",
                            "Support",
                            "BTS"
                        ],
                        element: [
                            "Light",
                            "Earth",
                            "Darkness",
                            "Water",
                            "Poison",
                            "Fire",
                            "Electricity",
                            "Ice",
                            "Wind",
                            "Steel",
                            "Grass",
                            "Chaos",
                            null
                        ],
                        position: [
                            "Front",
                            "Middle",
                            "Rear"
                        ]
                    },
                    tierlists: [
                        {
                    name: "World Exploration",
                            tiers: [
                                "S+",
                                "S",
                                "A+",
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ],
                    entries: [
                        [
                                    "Burning Spice Cookie",
                                    "Fire Spirit Cookie",
                            "Eternal Sugar Cookie",
                            "White Lily Cookie (Dawnbringer)",
                            "Pure Vanilla Cookie (Compassionate)",
                            "Hollyberry Cookie (Aegis)",
                                    "Cream Ferret Cookie",
                                    "Wind Archer Cookie",
                                    "Mystic Flour Cookie",
                                    "Silent Salt Cookie",
                            "Dark Enchantress Cookie",
                                    "Millennial Tree Cookie",
                                    "Rebel Cookie",
                                    "Sugar Swan Cookie",
                                    "Timekeeper Cookie"
                        ],
                        [
                                    "Stormbringer Cookie",
                                    "Crème Brûlée Cookie",
                            "Star Coral Cookie",
                                    "Marshmallow Bunny Cookie",
                                    "Twizzly Gummy Cookie",
                                    "Black Lemonade Cookie",
                                    "Pudding à la Mode Cookie",
                                    "Dark Cacao Cookie (Dragon Lord)",
                                    "Shadow Milk Cookie",
                                    "Nutmeg Tiger Cookie",
                                    "Grapefruit Cookie",
                                    "Silverbell Cookie",
                                    "Fettuccine Cookie",
                                    "Icicle Yeti Cookie",
                                    "Doughael",
                                    "Green Tea Mousse Cookie",
                                    "Financier Cookie",
                            "Mint Choco Cookie",
                                    "Sea Fairy Cookie",
                                    "Tarte Tatin Cookie",
                                    "Venom Dough Cookie",
                                    "Pure Vanilla Cookie",
                                    "Snapdragon Cookie",
                                    "Menthol Cookie",
                                    "Linzer Cookie"
                                ],
                                [
                                    "Golden Cheese Cookie (Immortal)",
                                    "Golden Cheese Cookie",
                            "White Lily Cookie",
                                    "Frost Queen Cookie",
                                    "Sherbet Cookie",
                                    "Pavlova Cookie",
                                    "Salt Cellar Cookie",
                            "Space Doughnut",
                                    "Jagae Cookie",
                                    "Manju Cookie",
                                    "Captain Caviar Cookie",
                                    "Candy Apple Cookie",
                                    "Seltzer Cookie",
                                    "Peach Blossom Cookie",
                                    "Moonlight Cookie",
                                    "Cream Puff Cookie",
                                    "Rockstar Cookie",
                                    "Mold Dough Cookie",
                            "Shining Glitter Cookie",
                                    "Mozzarella Cookie",
                                    "Sparkling Cookie",
                                    "Wedding Cake Cookie",
                                    "Parfait Cookie",
                                    "Snow Sugar Cookie",
                                    "Pom-pom Dough Cookie",
                                    "Charcoal Cookie"
                                ],
                                [
                                    "Hollyberry Cookie",
                                    "Crimson Coral Cookie",
                                    "Stardust Cookie",
                                    "Elder Faerie Cookie",
                                    "Camellia Cookie",
                                    "Burnt Cheese Cookie",
                                    "Kouign-Amann Cookie",
                                    "Cloud Haetae Cookie",
                            "Dark Choco Cookie",
                                    "Smoked Cheese Cookie",
                                    "Black Pearl Cookie",
                            "Capsaicin Cookie",
                                    "Pitaya Dragon Cookie",
                                    "Wildberry Cookie",
                                    "Peppermint Cookie",
                                    "Glinda Cookie",
                                    "Sugarfly Cookie",
                                    "Pinecone Cookie",
                                    "Milky Way Cookie",
                                    "Pastry Cookie",
                                    "Chess Choco Cookie",
                                    "Black Forest Cookie",
                                    "Lemon Cookie",
                                    "Cream Soda Cookie",
                                    "Mango Cookie",
                                    "Caramel Arrow Cookie",
                                    "Black Raisin Cookie",
                            "Schwarzwälder",
                                    "Frilled Jellyfish Cookie",
                                    "Street Urchin Cookie",
                                    "Clotted Cream Cookie",
                                    "Cream Unicorn Cookie",
                                    "Herb Cookie",
                            "Pomegranate Cookie"
                        ],
                        [
                                    "Dark Cacao Cookie",
                                    "Oyster Cookie",
                                    "Butter Roll Cookie",
                            "Mala Sauce Cookie",
                                    "Werewolf Cookie",
                                    "Espresso Cookie",
                                    "Strawberry Crepe Cookie",
                                    "Squid Ink Cookie",
                                    "Macaron Cookie",
                                    "Mercurial Knight Cookie",
                                    "Golden Osmanthus Cookie",
                                    "Red Osmanthus Cookie",
                                    "Eclair Cookie",
                                    "Cotton Cookie",
                            "Rye Cookie",
                                    "Madeleine Cookie",
                                    "Choco Drizzle Cookie",
                                    "Elphaba Cookie",
                                    "Orange Cookie",
                                    "Licorice Cookie",
                                    "Crunchy Chip Cookie",
                                    "Sorbet Shark Cookie",
                                    "Pumpkin Pie Cookie",
                                    "Carol Cookie",
                                    "Tea Knight Cookie",
                                    "Prune Juice Cookie",
                            "Black Sapphire Cookie",
                                    "Caramel Choux Cookie",
                                    "Okchun Cookie",
                                    "Matcha Cookie",
                                    "Affogato Cookie",
                                    "Royal Margarine Cookie",
                            "Blackberry Cookie",
                                    "Cherry Blossom Cookie",
                                    "BTS"
                        ],
                        [
                                    "Purple Yam Cookie",
                                    "Raspberry Cookie",
                                    "Blueberry Pie Cookie",
                            "Lime Cookie",
                                    "Vampire Cookie",
                                    "Red Velvet Cookie",
                                    "Latte Cookie",
                                    "Prophet Cookie",
                                    "Moon Rabbit Cookie",
                            "Agar Agar Cookie",
                                    "Olive Cookie",
                                    "Poison Mushroom Cookie",
                                    "Candy Diver Cookie",
                                    "Almond Cookie",
                                    "Carrot Cookie",
                            "Kumiho Cookie"
                        ],
                        [
                                    "Chili Pepper Cookie",
                                    "Milk Cookie",
                                    "Lilac Cookie",
                            "Cherry Cookie",
                                    "Sonic Cookie",
                                    "Tails Cookie",
                                    "Knight Cookie",
                                    "Avocado Cookie",
                                    "Tiger Lily Cookie",
                                    "Cocoa Cookie",
                            "Devil Cookie",
                                    "Princess Cookie",
                                    "Custard Cookie III",
                                    "Wizard Cookie",
                                    "Pancake Cookie",
                                    "Gumball Cookie",
                            "Alchemist Cookie",
                            "Clover Cookie"
                        ],
                        [
                                    "GingerBrave",
                                    "Fig Cookie",
                                    "Onion Cookie",
                            "Strawberry Cookie",
                                    "Muscle Cookie",
                                    "Beet Cookie",
                                    "Adventurer Cookie",
                                    "Ninja Cookie",
                                    "Angel Cookie"
                                ]
                            ]
                        },
                        {
                    name: "Kingdom Arena",
                            tiers: [
                                "S+",
                                "S",
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ],
                    entries: [
                        [
                                    "Dark Enchantress Cookie",
                                    "Silent Salt Cookie",
                            "Millennial Tree Cookie",
                            "Venom Dough Cookie",
                            "White Lily Cookie (Dawnbringer)",
                                    "Eternal Sugar Cookie",
                                    "Sugar Swan Cookie",
                                    "Timekeeper Cookie"
                        ],
                        [
                                    "Cream Ferret Cookie",
                                    "Icicle Yeti Cookie",
                            "Hollyberry Cookie (Aegis)",
                            "Pure Vanilla Cookie (Compassionate)",
                                    "Shadow Milk Cookie",
                                    "Marshmallow Bunny Cookie"
                        ],
                        [
                                    "Stormbringer Cookie",
                                    "Doughael",
                            "Golden Cheese Cookie (Immortal)",
                                    "Burning Spice Cookie",
                                    "Elder Faerie Cookie",
                                    "Green Tea Mousse Cookie",
                                    "Rockstar Cookie",
                            "Wildberry Cookie",
                                    "Dark Cacao Cookie (Dragon Lord)",
                                    "Moonlight Cookie",
                                    "Financier Cookie",
                                    "Snapdragon Cookie",
                                    "Camellia Cookie",
                                    "Fire Spirit Cookie",
                                    "Mystic Flour Cookie",
                                    "Wind Archer Cookie"
                                ],
                                [
                                    "Pure Vanilla Cookie",
                                    "White Lily Cookie",
                            "Golden Cheese Cookie",
                                    "Frost Queen Cookie",
                                    "Sea Fairy Cookie",
                                    "Rebel Cookie",
                                    "Burnt Cheese Cookie",
                                    "Salt Cellar Cookie",
                            "Pavlova Cookie",
                                    "Stardust Cookie",
                                    "Black Forest Cookie",
                                    "Chess Choco Cookie",
                                    "Wedding Cake Cookie",
                                    "Raspberry Cookie",
                                    "Star Coral Cookie",
                                    "Silverbell Cookie",
                                    "Blueberry Pie Cookie",
                                    "Captain Caviar Cookie",
                                    "Manju Cookie",
                            "Jagae Cookie",
                                    "Pastry Cookie",
                                    "Kouign-Amann Cookie",
                                    "Mold Dough Cookie",
                                    "Charcoal Cookie",
                                    "Dark Choco Cookie",
                                    "Cloud Haetae Cookie",
                                    "Mint Choco Cookie",
                                    "Parfait Cookie",
                                    "Peach Blossom Cookie",
                                    "Candy Apple Cookie",
                            "Twizzly Gummy Cookie",
                                    "Pudding à la Mode Cookie",
                                    "Nutmeg Tiger Cookie",
                                    "Grapefruit Cookie",
                                    "Crème Brûlée Cookie",
                                    "Tea Knight Cookie",
                                    "Strawberry Crepe Cookie",
                                    "Black Lemonade Cookie",
                                    "Seltzer Cookie",
                                    "Menthol Cookie",
                                    "Capsaicin Cookie",
                                    "Shining Glitter Cookie",
                                    "Sherbet Cookie",
                            "Smoked Cheese Cookie",
                                    "Mercurial Knight Cookie",
                                    "Milky Way Cookie",
                            "Choco Drizzle Cookie",
                                    "Space Doughnut",
                                    "Snow Sugar Cookie",
                                    "Crimson Coral Cookie",
                            "Fettuccine Cookie",
                                    "Hollyberry Cookie",
                                    "Frilled Jellyfish Cookie",
                            "Pom-pom Dough Cookie"
                        ],
                        [
                                    "Dark Cacao Cookie",
                                    "Pitaya Dragon Cookie",
                            "Black Pearl Cookie",
                                    "Clotted Cream Cookie",
                                    "Cream Unicorn Cookie",
                                    "Sugarfly Cookie",
                                    "Vampire Cookie",
                                    "Cream Puff Cookie",
                            "Mozzarella Cookie",
                                    "Linzer Cookie",
                                    "Golden Osmanthus Cookie",
                                    "Red Osmanthus Cookie",
                                    "Cream Soda Cookie",
                            "Sorbet Shark Cookie",
                                    "Madeleine Cookie",
                                    "Mango Cookie",
                                    "Peppermint Cookie",
                                    "Schwarzwälder",
                                    "Street Urchin Cookie",
                            "Pinecone Cookie",
                                    "Almond Cookie",
                                    "Squid Ink Cookie",
                                    "Black Raisin Cookie",
                                    "Herb Cookie",
                                    "Werewolf Cookie",
                            "Prune Juice Cookie",
                                    "Black Sapphire Cookie",
                                    "Butter Roll Cookie",
                                    "Mala Sauce Cookie",
                                    "Macaron Cookie",
                                    "Purple Yam Cookie",
                            "Lemon Cookie",
                                    "Orange Cookie",
                                    "Latte Cookie",
                                    "Crunchy Chip Cookie",
                                    "Espresso Cookie",
                                    "Eclair Cookie",
                            "Prophet Cookie",
                            "Royal Margarine Cookie",
                                    "Pumpkin Pie Cookie",
                                    "Caramel Arrow Cookie",
                            "Caramel Choux Cookie",
                                    "Tarte Tatin Cookie",
                                    "Rye Cookie",
                                    "Licorice Cookie",
                                    "Agar Agar Cookie",
                                    "Carol Cookie",
                            "Cotton Cookie",
                                    "Pomegranate Cookie",
                                    "Lime Cookie",
                                    "Matcha Cookie",
                                    "Oyster Cookie",
                                    "Okchun Cookie",
                            "Glinda Cookie",
                                    "Elphaba Cookie",
                                    "BTS",
                                    "Blackberry Cookie"
                        ],
                        [
                                    "Red Velvet Cookie",
                                    "Olive Cookie",
                                    "Affogato Cookie",
                            "Cocoa Cookie",
                                    "Milk Cookie",
                                    "Poison Mushroom Cookie",
                                    "Candy Diver Cookie",
                                    "Cherry Blossom Cookie",
                                    "Kumiho Cookie",
                                    "Sparkling Cookie",
                                    "Tiger Lily Cookie",
                                    "Lilac Cookie",
                                    "Moon Rabbit Cookie",
                                    "Carrot Cookie"
                                ],
                                [
                                    "Chili Pepper Cookie",
                                    "Fig Cookie",
                                    "Sonic Cookie",
                            "Tails Cookie",
                                    "GingerBrave",
                                    "Onion Cookie",
                                    "Strawberry Cookie",
                                    "Muscle Cookie",
                                    "Beet Cookie",
                                    "Adventurer Cookie",
                                    "Ninja Cookie",
                                    "Angel Cookie",
                                    "Knight Cookie",
                                    "Avocado Cookie",
                                    "Devil Cookie",
                                    "Princess Cookie",
                                    "Custard Cookie III",
                                    "Wizard Cookie",
                                    "Pancake Cookie",
                                    "Gumball Cookie",
                            "Alchemist Cookie",
                                    "Clover Cookie",
                                    "Cherry Cookie"
                        ]
                    ]
                        },
                        {
                    name: "Overall (avg)",
                    computedAverage: true,
                            tiers: [
                                "S+",
                                "S",
                                "A+",
                                "A",
                                "B",
                                "C",
                                "D",
                                "E",
                                "F"
                            ],
                    entries: []
                        },
                        {
                    name: "Guild Battle",
                            tierlists: [
                                {
                        name: "Red Velvet Dragon",
                                    tiers: [
                                        "S",
                                        "A",
                                        "B",
                                        "C",
                                        "D",
                                        "E"
                                    ],
                        entries: [
                            [
                                            "Black Sapphire Cookie",
                                            "Prune Juice Cookie",
                                            "Shadow Milk Cookie",
                                            "Candy Apple Cookie",
                                            "Dark Choco Cookie",
                                            "Pom-pom Dough Cookie",
                                "Venom Dough Cookie"
                            ],
                            [
                                            "Matcha Cookie",
                                            "Rebel Cookie",
                                "Mystic Flour Cookie",
                                "Twizzly Gummy Cookie",
                                            "Black Lemonade Cookie",
                                            "Eternal Sugar Cookie",
                                            "Fire Spirit Cookie",
                                            "Burning Spice Cookie",
                                "Dark Cacao Cookie (Dragon Lord)",
                                "Pure Vanilla Cookie (Compassionate)",
                                "Black Raisin Cookie",
                                            "Rockstar Cookie",
                                            "Royal Margarine Cookie",
                                            "Snapdragon Cookie",
                                            "Cream Ferret Cookie",
                                            "Stormbringer Cookie",
                                            "Shining Glitter Cookie",
                                            "Pudding à la Mode Cookie",
                                            "Orange Cookie",
                                            "Lemon Cookie",
                                            "Linzer Cookie",
                                            "Mango Cookie",
                                            "Stardust Cookie",
                                            "Milky Way Cookie",
                                            "Eclair Cookie",
                                            "Space Doughnut",
                                "Snow Sugar Cookie",
                                            "Cotton Cookie",
                                            "Sherbet Cookie",
                                            "Affogato Cookie",
                                            "Vampire Cookie",
                                "Oyster Cookie",
                                            "Sorbet Shark Cookie",
                                            "Pomegranate Cookie",
                                            "Crunchy Chip Cookie",
                                            "Licorice Cookie",
                                            "Poison Mushroom Cookie",
                                            "Cream Unicorn Cookie",
                                            "Cream Puff Cookie",
                                            "Golden Cheese Cookie",
                                            "Peach Blossom Cookie",
                                            "Choco Drizzle Cookie",
                                            "Cream Soda Cookie",
                                            "BTS",
                                            "Pure Vanilla Cookie",
                                            "Seltzer Cookie",
                                            "Doughael"
                                        ],
                                        [
                                            "Hollyberry Cookie (Aegis)",
                                            "Pinecone Cookie",
                                            "Captain Caviar Cookie",
                                            "Fettuccine Cookie",
                                            "Cocoa Cookie",
                                            "Peppermint Cookie",
                                "Macaron Cookie",
                                            "Carol Cookie",
                                            "Almond Cookie",
                                            "Raspberry Cookie",
                                            "Rye Cookie",
                                "Mala Sauce Cookie",
                                            "Hollyberry Cookie",
                                            "Schwarzwälder",
                                            "Pumpkin Pie Cookie",
                                            "Parfait Cookie",
                                "Wildberry Cookie",
                                            "Capsaicin Cookie",
                                            "Prophet Cookie",
                                            "Crimson Coral Cookie",
                                            "Menthol Cookie"
                                        ],
                                        [
                                            "Dark Cacao Cookie",
                                            "Herb Cookie",
                                "Silverbell Cookie",
                                            "Espresso Cookie",
                                            "Moonlight Cookie",
                                            "Pitaya Dragon Cookie",
                                            "Sea Fairy Cookie",
                                "Squid Ink Cookie",
                                "Tea Knight Cookie",
                                            "Black Pearl Cookie",
                                            "Tarte Tatin Cookie",
                                            "Blueberry Pie Cookie",
                                            "Candy Diver Cookie",
                                            "Strawberry Crepe Cookie",
                                            "Moon Rabbit Cookie",
                                            "Kumiho Cookie",
                                            "Frilled Jellyfish Cookie",
                                "Olive Cookie"
                            ],
                            [
                                            "Wind Archer Cookie",
                                            "Crème Brûlée Cookie",
                                            "Kouign-Amann Cookie",
                                            "Financier Cookie",
                                            "Werewolf Cookie",
                                            "Caramel Arrow Cookie",
                                "Latte Cookie",
                                            "Sparkling Cookie",
                                            "Madeleine Cookie",
                                            "Pastry Cookie",
                                            "Lilac Cookie",
                                            "Mint Choco Cookie"
                                        ],
                                        [
                                            "Milk Cookie",
                                            "Purple Yam Cookie",
                                "Chili Pepper Cookie",
                                            "Red Velvet Cookie",
                                            "Tiger Lily Cookie",
                                            "White Lily Cookie",
                                            "Frost Queen Cookie",
                                            "Clotted Cream Cookie",
                                            "Cherry Blossom Cookie",
                                "Fig Cookie"
                            ]
                        ]
                                },
                                {
                        name: "Avatar of Destiny",
                                    tiers: [
                                        "S",
                                        "A"
                                    ],
                        entries: [
                            [
                                "Crème Brûlée Cookie",
                                "Pudding à la Mode Cookie",
                                "Star Coral Cookie",
                                "Cream Ferret Cookie",
                                "Mint Choco Cookie"
                            ],
                            [
                                "Twizzly Gummy Cookie",
                                "Marshmallow Bunny Cookie",
                                "Icicle Yeti Cookie",
                                "Blackberry Cookie",
                                "Cream Puff Cookie",
                                "Madeleine Cookie",
                                "Sonic Cookie",
                                "Macaron Cookie",
                                "Squid Ink Cookie",
                                "Cherry Blossom Cookie",
                                "Caramel Choux Cookie",
                                "Shining Glitter Cookie",
                                "Rye Cookie",
                                "Rockstar Cookie",
                                "Lime Cookie",
                                "Pomegranate Cookie",
                                "Oyster Cookie",
                                "Snapdragon Cookie",
                                "BTS",
                                "Sugarfly Cookie",
                                "Parfait Cookie",
                                "Clotted Cream Cookie",
                                "Pastry Cookie",
                                "Peppermint Cookie",
                                "Carol Cookie",
                                "Tails Cookie",
                                "Carrot Cookie",
                                "Vampire Cookie",
                                "Lemon Cookie"
                            ]
                        ]
                                },
                                {
                        name: "Living Abyss",
                                    tiers: [
                                        "S",
                                        "A",
                                        "B",
                                        "C",
                                        "D",
                                        "E"
                                    ],
                        entries: [
                            [
                                "Blueberry Pie Cookie",
                                "Wind Archer Cookie",
                                "Cream Puff Cookie",
                                "Marshmallow Bunny Cookie",
                                "Cream Ferret Cookie",
                                "Linzer Cookie",
                                "Black Forest Cookie",
                                "Twizzly Gummy Cookie",
                                "Eternal Sugar Cookie",
                                "Wedding Cake Cookie"
                            ],
                            [
                                "Frost Queen Cookie",
                                "Pinecone Cookie",
                                "Star Coral Cookie",
                                "Rockstar Cookie",
                                "Rebel Cookie",
                                "Fire Spirit Cookie",
                                "Stormbringer Cookie",
                                "Pitaya Dragon Cookie",
                                "Burning Spice Cookie",
                                "Shadow Milk Cookie",
                                "Pure Vanilla Cookie (Compassionate)",
                                "Dark Cacao Cookie (Dragon Lord)",
                                "Macaron Cookie",
                                "Space Doughnut",
                                "Snow Sugar Cookie",
                                "Snapdragon Cookie",
                                "Captain Caviar Cookie",
                                "Caramel Arrow Cookie",
                                "Black Raisin Cookie",
                                "Squid Ink Cookie",
                                "Candy Apple Cookie",
                                "Milky Way Cookie",
                                "Cotton Cookie",
                                "Mango Cookie",
                                "Werewolf Cookie",
                                "Schwarzwälder",
                                "Dark Cacao Cookie",
                                "Sherbet Cookie",
                                "Crème Brûlée Cookie",
                                "Black Pearl Cookie",
                                "Sea Fairy Cookie",
                                "Moonlight Cookie",
                                "Espresso Cookie",
                                "Shining Glitter Cookie",
                                "Tarte Tatin Cookie",
                                "Pomegranate Cookie",
                                "Mystic Flour Cookie",
                                "Pure Vanilla Cookie",
                                "Peach Blossom Cookie",
                                "Silverbell Cookie",
                                "Sorbet Shark Cookie",
                                "Clotted Cream Cookie",
                                "Crunchy Chip Cookie",
                                "Dark Choco Cookie",
                                "Wildberry Cookie",
                                "Cherry Blossom Cookie",
                                "White Lily Cookie",
                                "Latte Cookie",
                                "Oyster Cookie",
                                "Carol Cookie",
                                "BTS",
                                "Parfait Cookie",
                                "Golden Cheese Cookie",
                                "Purple Yam Cookie",
                                "Street Urchin Cookie",
                                "Stardust Cookie",
                                "Peppermint Cookie"
                            ],
                            [
                                "Fettuccine Cookie",
                                "Hollyberry Cookie",
                                "Pumpkin Pie Cookie",
                                "Licorice Cookie",
                                "Herb Cookie",
                                "Cream Unicorn Cookie",
                                "Frilled Jellyfish Cookie",
                                "Mercurial Knight Cookie",
                                "Kouign-Amann Cookie",
                                "Tea Knight Cookie",
                                "Burnt Cheese Cookie",
                                "Butter Roll Cookie",
                                "Financier Cookie",
                                "Madeleine Cookie",
                                "Capsaicin Cookie",
                                "Mala Sauce Cookie"
                            ],
                            [
                                "Crimson Coral Cookie",
                                "Cocoa Cookie",
                                "Black Lemonade Cookie",
                                "Vampire Cookie",
                                "Rye Cookie",
                                "Eclair Cookie",
                                "Strawberry Crepe Cookie",
                                "Milk Cookie",
                                "Poison Mushroom Cookie",
                                "Matcha Cookie",
                                "Candy Diver Cookie",
                                "Cloud Haetae Cookie",
                                "Sparkling Cookie",
                                "Mint Choco Cookie",
                                "Pastry Cookie",
                                "Kumiho Cookie",
                                "Prophet Cookie",
                                "Olive Cookie",
                                "Lilac Cookie"
                            ],
                            [
                                "Affogato Cookie",
                                "Almond Cookie",
                                "Moon Rabbit Cookie",
                                "Caramel Choux Cookie"
                            ],
                            [
                                "Chili Pepper Cookie",
                                "Fig Cookie",
                                "Red Velvet Cookie",
                                "Tiger Lily Cookie",
                                "Raspberry Cookie",
                                "Royal Margarine Cookie",
                                "Prune Juice Cookie",
                                "Black Sapphire Cookie"
                            ]
                        ]
                                },
                                {
                        name: "Machine-God of the Eternal Void",
                                    tiers: [
                                        "S",
                                        "A",
                                        "B",
                                        "C"
                                    ],
                        entries: [
                            [
                                "Menthol Cookie",
                                "Seltzer Cookie",
                                "Sea Fairy Cookie",
                                "Frilled Jellyfish Cookie",
                                "Cream Ferret Cookie",
                                "Cream Soda Cookie"
                            ],
                            [
                                "Crimson Coral Cookie",
                                "Black Pearl Cookie",
                                "Peppermint Cookie",
                                "Captain Caviar Cookie",
                                "Star Coral Cookie",
                                "Manju Cookie",
                                "Jagae Cookie"
                            ],
                            [
                                "Mango Cookie",
                                "Sorbet Shark Cookie",
                                "Snapdragon Cookie",
                                "Marshmallow Bunny Cookie",
                                "Icicle Yeti Cookie"
                            ],
                            [
                                "Squid Ink Cookie",
                                "Agar Agar Cookie"
                            ]
                        ]
                                }
                            ]
                        }
                    ]
                },
                {
                name: "Magic Candies",
                features: {
                    eidolon: false,
                    tags: false,
                    elementIcon: false,
                    role: false,
                    cardStyle: "candy"
                },
                    tierlists: [
                        {
                    name: "World Exploration",
                            tiers: [
                                "S",
                                "A",
                                "B",
                                "C",
                                "D",
                                "F"
                            ],
                    entries: [
                                [
                                    "Wind Archer",
                                    "Stormbringer",
                                    "Twizzly Gummy",
                                    "Captain Caviar"
                                ],
                                [
                                    "Frost Queen",
                                    "Blueberry Pie",
                                    "Mango",
                                    "Dark Choco",
                                    "Black Raisin",
                                    "Pastry",
                                    "Cream Puff",
                                    "Caramel Arrow",
                                    "Kouign-Amann",
                            "Green Tea Mousse"
                        ],
                                [
                                    "Sea Fairy",
                                    "Moonlight",
                                    "Mint Choco",
                                    "Frilled Jellyfish",
                            "Pinecone",
                                    "Financier",
                                    "Parfait",
                                    "Peppermint",
                                    "Strawberry Crepe",
                                    "Snow Sugar",
                                    "Raspberry",
                            "Squid Ink",
                                    "Werewolf",
                                    "Silverbell"
                                ],
                                [
                                    "Black Pearl",
                                    "Sparkling",
                                    "Cream Unicorn",
                                    "Mala Sauce",
                                    "Licorice",
                                    "Rye",
                                    "Madeleine",
                                    "Tea Knight",
                                    "Vampire"
                                ],
                                [
                                    "Latte",
                                    "Espresso",
                                    "Milk",
                                    "Sorbet Shark",
                                    "Purple Yam",
                                    "Wildberry",
                                    "Pomegranate",
                                    "Poison Mushroom"
                        ],
                        []
                    ]
                        },
                        {
                    name: "Kingdom Arena",
                            tiers: [
                                "S",
                                "A",
                                "B",
                                "C",
                                "D",
                                "F"
                            ],
                    entries: [
                                [
                                    "Wind Archer",
                                    "Financier",
                                    "Stormbringer"
                                ],
                                [
                                    "Moonlight",
                                    "Frost Queen",
                                    "Sea Fairy",
                                    "Black Pearl"
                                ],
                                [
                                    "Wildberry",
                                    "Vampire",
                                    "Raspberry",
                                    "Captain Caviar",
                            "Caramel Arrow",
                                    "Blueberry Pie",
                                    "Parfait",
                                    "Green Tea Mousse"
                        ],
                        [
                                    "Tea Knight",
                                    "Dark Choco",
                                    "Twizzly Gummy",
                                    "Strawberry Crepe",
                            "Sorbet Shark",
                                    "Snow Sugar",
                                    "Black Raisin",
                                    "Pastry",
                                    "Mango",
                                    "Kouign-Amann",
                                    "Mala Sauce",
                                    "Cream Puff",
                                    "Mint Choco",
                                    "Werewolf",
                            "Frilled Jellyfish",
                                    "Peppermint",
                                    "Pinecone",
                                    "Squid Ink",
                                    "Rye",
                                    "Madeleine",
                                    "Espresso",
                                    "Silverbell"
                                ],
                                [
                                    "Sparkling",
                                    "Latte",
                                    "Cream Unicorn",
                                    "Purple Yam",
                                    "Licorice",
                                    "Milk",
                                    "Pomegranate",
                                    "Poison Mushroom"
                        ],
                        []
                    ]
                        }
                    ]
                }
            ]
});
