// Generated by import_wiki_skill_details.py
window.WIKI_IMPORTED_SKILL_DETAILS = {
  "wikiApi": "https://cookierun.wiki/mw/api.php",
  "cookies": {
    "Ash_salt": {
      "wikiTitle": "Ash Salt Cookie/Kingdom",
      "keys": {
        "ash_salt": {
          "skill_details": "DMG: darkness{%{attr1}} of ATK<br>DMG (Bosses): darkness{%{attr2}} of ATK<br>Shadow Form Transformation: 10 sec<br>Shadow Form: status{ATK_Up|und_buff} ATK +17.5%, status{ATK_SPD_Up|und_buff} ATK SPD +25.0%, status{DMG_Dampening|und_buff} DMG Dampening hover{Written as '+' in-game:-}15.0% for 10 sec<br>Shadow Form Regular Attack DMG: darkness{150.0%} of ATK<br>Final Hit DMG: darkness{208.9%} of ATK<br>Ashen Salt DMG: 35.4% every 1 sec for 10 sec; hover{Not mentioned in-game:stacks up to x1}<br>Cooldown: -1.0% of remaining Cooldown per status{Salt_Crystal} Salt Crystal, up to x10 Salt Crystals<br>status{Consuming_Darkness} Consuming Darkness: CRIT% -5.0% + Healing Received -5.0% for 8 sec; stacks up to x3",
          "skillAttr": {
            "attr1": [
              157.3,
              449.3
            ],
            "attr2": [
              235.9,
              674.0
            ]
          }
        }
      },
      "warnings": []
    }
  }
};
