// Generated by import_wiki_cookie_data.py — cookies[] → data.js characters; descriptions → merge into crk/crk_descriptions.js (or replace when doing a full regen).
window.WIKI_IMPORTED_COOKIE_DATA = {
    wikiApi: "https://cookierun.wiki/mw/api.php",
    cookies: [
        {
            name: "Ananas_dragon",
            element: "Earth",
            type: "Magic",
            position: "Middle",
            rarity: "Dragon",
            skill: "Golden Awakening",
            cd: 14
        }
    ],
    descriptions: {
        description: {
            ananas_dragon: "From the skies appeared a dragon with noble, golden scales as radiant as the sun. Upon the island's tallest peak did the dragon decide to perch. All denizens of the island looked up in awe and presented various fruits as offerings. The island was home to blooming vibrant flowers and breathtaking waterfalls: a true paradise. Overflowing with pride in the prestige and power of Dragonkind, the dragon reigned supreme over the island At times a merciful and benevolent protector, but in others a fearsome and relentless oppressor. And suddenly, disaster struck. The towering offerings of fruit collapsed during a devastating earthquake. Rains and winds hammered the tower's remnants, concealing the once glimmering light. From the chasm appeared a small figure made of dough, reclusing themselves from sight. The biding of time continues, for the day of spreading their wings in full glory has not yet arrived."
        },
        skill_description: {
            ananas_dragon: "As the Song of Dragontongue resonates, Ananas Dragon Cookie reclaims their ancient power and transforms into a mighty dragon, granting HP Shields and Golden Dragontongue to the team. Ananas Dragon Cookie unleashes a powerful roar and gains Dragon's Power. Additionally, inflicts Fear on all enemies, applies Ananas Dragon's Rage, and summons a Meteor, dealing damage. Fear from the roar cannot be removed by Purify and is not affected by Debuff Resist. Ananas Dragon Cookie then soars into the sky and crashes down, dealing damage, Knocking enemies back, and sending them Airborne.<br><br>Gains Energy of the Earthbread; at max stacks, applies Rock Seal to their target. As the master of the earthbread, Ananas Dragon Cookie is immune to Rock Seal. At the start of battle, if Ananas Dragon Cookie's Beascuit has 2 or more Earth-type DMG Up bonus effects, Dragon's Power is enhanced."
        }
    }
};
