// Generated by import_wiki_cookie_data.py — cookies[] → data.js characters; descriptions → merge into crk/crk_descriptions.js (or replace when doing a full regen).
window.WIKI_IMPORTED_COOKIE_DATA = {
    wikiApi: "https://cookierun.wiki/mw/api.php",
    cookies: [
        {
            name: "Silverbell",
            element: "Grass",
            type: "Support",
            position: "Rear",
            rarity: "Epic",
            skill: "Gleeful Chime",
            cd: 15,
            mcSkill: "Verdant Chime"
        }
    ],
    descriptions: {
        description: {
            silverbell: "If you ever encounter a wisp of white light, wandering across the misty trees with a cheerful chiming, do not let your guard down. For Silverbell Cookie will never miss a shot. Resembling a soft flower petal adorned with beads of morning dew, Silverbell Cookie is not as delicate as he might seem. As a loyal Knight of the Faerie Kingdom, he has sworn to protect its secrets with his life. And yet, despite the heavy burden of his duty, this Cookie always keeps a pure, bright smile—after all, there is all, there is no stronger shield than a loving heart."
        },
        skill_description: {
            silverbell: "Silverbell flowers bloom, periodically healing the allies and granting a DMG Resist buff. Healing targets will also receive bonus healing depending on the number of buffs they currently have. Enemies will receive damage and gain the Silverbell Pollen debuff dealing periodic damage. When Silverbell Pollen's duration is over, it will cause area damage and Stun the targets in range. Silverbell Cookie is immune to the Spore Dispersal and Mushroom Mutation effects. Entering the battle with Mercurial Knight Cookie will activate the color-header{A3CCC5:Silver Knighthood} effect.",
            silverbell_mc: "Silverbell flowers bless the nearby allies, Healing them and increasing their Grass-type DMG, Debuff Resist, and Healing received. Gleeful Chime's targets will be stunned and receive increased Grass-type DMG."
        }
    }
};
