// Generated by import_wiki_skill_details.py
window.WIKI_IMPORTED_SKILL_DETAILS = {
  "wikiApi": "https://cookierun.wiki/mw/api.php",
  "cookies": {
    "Sugar_swan": {
      "wikiTitle": "Sugar Swan Cookie/Kingdom",
      "keys": {
        "sugar_swan": {
          "skill_details": "Sugar Feather Healing: status{Healing} heals all allies for %{attr1} of ATK every 0.25 sec for 1.25 sec + 1.28% of target's Max HP<br>status{Sweet_Sugar_Feather} Sweet Sugar Feather: DMG Resist +10.0%, DMG Dampening -26.0%, CRIT Resist +17.5%, ATK +45.0% for all allies for 20 sec; stacks up to x1<br>Sugar Feather Single-hit DMG: light{675.4%} of ATK<br>status{Blessing_of_Light} Blessing of Light: Amplify Buff +10.0%, DMG Resist +15.0% for 20 sec upon using skill; stacks up to x1<br>color-header{FCB0FF:Guardian of Life}<br>Revives ally Cookies up to x2 times per battle (x1 if treasure{sugar_swans_shining_feather} Sugar Swan's Shining Feather Treasure is equipped)<br>Revival: revives with 100% HP + status{HP_Shield} HP Shield equal to 10.0% of Max HP for 5 sec<br>color-header{FCB0FF:Swan Transformation & Galaxy Lake}<br>Swan Form: 6 sec<br>Galaxy Lake Healing: status{Healing} heals allies (excluding self) in the Galaxy Lake for %{attr2} of ATK + 0.8% of target's Max HP every 0.7 sec<br>status{Galaxy_Lake_Sanctuary} Galaxy Lake Sanctuary: DMG Resist +35.0%, Amplify Buff +17.5%, Debuff Resist +25.0% for allies (excluding self) in the Galaxy Lake every 0.7 sec; stacks up to x1<br>Swan's Final Protection: status{Healing} heals all allies (excluding self) for 3.0% of Max HP every 0.1 sec for 0.9 sec; removes debuffs<br>color-header{FCB0FF:Breath of Life}<br>status{Max_HP_Up|und_buff} Max HP +30.0%, status{DMG_Down|und_buff} DMG Resist +30.0%, status{DMG_Dampening|und_buff} DMG Dampening +27.5%<br>If there are 2 Revivals left: additional status{DMG_Dampening|und_buff} DMG Dampening +62.5%<br>color-header{FCB0FF:Aura of Vitality}<br>Healing +0.8% for every 1.0% of ATK gained from Toppings (capped at 35.0%)",
          "skillAttr": {
            "attr1": [
              21.0,
              60.1
            ],
            "attr2": [
              21.5,
              61.3
            ]
          },
          "skill_notes": "Regular attacks heal the lowest HP ally for 43.3% of ATK.<br>Becomes intangible while using the skill."
        }
      },
      "warnings": []
    }
  }
};
