// Generated by import_wiki_cookie_data.py — cookies[] → data.js characters; descriptions → merge into crk/crk_descriptions.js (or replace when doing a full regen).
window.WIKI_IMPORTED_COOKIE_DATA = {
    wikiApi: "https://cookierun.wiki/mw/api.php",
    cookies: [
        {
            name: "Wind_archer",
            displayName: "Wind Archer Cookie",
            element: "Wind",
            type: "Ranged",
            position: "Rear",
            rarity: "Legendary",
            skill: "Last Wind",
            cd: 6,
            cjSkill: "Last Gale"
        }
    ],
    descriptions: {
        description: {},
        skill_description: {
            wind_archer: "Upon transforming, Wind Archer Cookie removes all debuffs from himself, then shoots his Arrow of Gale, pushing back and stunning enemies, and applies the Trace of the Wind and Pursuer debuffs. While transformed, he will become immune to debuffs except for Curse and will shoot his Pursuer's Arrows with his attacks.\n\nThe Pursuer's Arrow attacks up to five enemies with the highest ATK and applies the Trace of the Wind and Pursuer debuffs to its targets. Once Pursuer reaches max stacks, it will explode and inflict damage proportional to the targets' Max HP, damage nearby enemies, and apply the Trace of the Wind debuff. Wind Archer Cookie applies the Mighty Gale buff to himself whenever he shoots the Pursuer's Arrow.\n\nThis Guardian Cookie casts Last Wind, which partially ignores the target's DMG Resist and inflicts additional damage to enemies proportional to the number of Mighty Gale stacks. Affected enemies will be trapped in a Cyclone. When entering the battle, Wind Archer Cookie's Max HP increases. (DMG proportional to Max HP is capped at 300,000.)",
            wind_archer_cj: "The power of the wind becomes amplified with the Crystal Jam, changing Wind Archer Cookie's skill, and increasing his DMG Resist at the start of battle with the Wind's Protection. Pursuer's Arrow becomes enhanced, increasing the number of arrows fired during transformation based on the ATK SPD boost rate and dealing area DMG to enemies nearby the target hit. Additionally, the Cooldown after Pursuer's Arrow has triggered is decreased. When the Mighty Gale buff reaches the maximum number of stacks, Wind Archer Cookie gains the Howling Gust buff. The final shot of Last Wind becomes Last Gale, blasting through the enemy lines and causing Afterstorm. If Howling Gust is active, Afterstorm deals additional DMG."
        }
    }
};
